# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker_files/backend.Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: ./docker_files/frontend_1.Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend_1:/app
      - /app/node_modules
      - /app/.next
